stages:
  - test
  - deploy

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: SAST.gitlab-ci.yml
  - template: Code-Quality.gitlab-ci.yml

# Make quality report downloadable
code_quality:
  rules:
    - if: '$CI_COMMIT_TAG == null'
  artifacts:
    paths: [gl-code-quality-report.json]

sast:
  variables:
    SAST_EXCLUDED_PATHS: test/**

# Lint js files
lint-js:
  rules:
    - if: '$CI_COMMIT_TAG == null'
  image: node
  stage: test
  tags:
    - docker
  script:
    - npm i -g eslint
    - eslint --ignore-pattern "**/*.min.js" $CI_PROJECT_DIR

# Performs unit testing
unit-test:
  coverage: '/Statements\s*:\s*(\d+(?:\.\d+)?\%)/'
  image: registry.gitlab.com/gcsboss/docker-mocha-nyc:0.1.0-alpine
  stage: test
  artifacts:
    paths: [coverage]
  tags:
    - docker
  script:
    - npm i .
    - npm run coverage

# Publish package to NPM
publish:
  stage: deploy
  image: node
  tags:
    - docker
  only:
    - tags
    - triggers
  script:
    - npm i -g npm-cli-login
    - npm-cli-login
    - npm publish
